language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word
  min_ngram: 1
  max_ngram: 1
  max_features: 10000
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
  max_features: 20000

- name: DIETClassifier
  epochs: 60                # ok to keep decent
  batch_size: [4, 16]       # ↓ batch to cut memory
  number_of_transformer_layers: 1
  transformer_size: 32       # 32 or 64; 32 is very light
  drop_rate: 0.3
  embedding_dimension: 20
  constrain_similarities: true
  batch_strategy: "sequence"     # keeps batches small for long seqs
  learning_rate: 0.001

- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 30
  batch_size: [4, 16]
  transformer_size: 32
  number_of_transformer_layers: 1
  drop_rate: 0.3
assistant_id: 20250912-161419-tender-collateral
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
