recipe: default.v1
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: DIETClassifier
    epochs: 60
    constrain_similarities: true     # <- add this
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.35
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
    epochs: 50
    constrain_similarities: true     # <- add this
assistant_id: 20250816-194459-fresh-clone
